<?php

class Block extends House
{
    public $flats;

    static $col;

    public function buildHouse($o, $r, $w, $wnd, $f,$fl)
    {
        parent::buildHouse($o, $r, $w, $wnd, $f); // TODO: Change the autogenerated stub
        $this->flats = $fl;
    }

}